<?php

namespace Core\Validation;

class InList extends Validator
{
    public function __construct($rule)
    {
        parent::__construct($rule); // TODO: Change the autogenerated stub
    }

    function validate($value): bool
    {
        $flag = false;
        foreach ($this->rule as $item){
            if ($item === $value) {
                $flag = true;
            }
        }
        return $flag;
    }
}